=head1 NAME

SVK::Help::Index - SVK Documentation - Main index

=head1 DESCRIPTION

If this is your first time using SVK, you should start by reading a 
brief tutorial. When you're ready, type:

    svk help intro

Once you've done that, more in-depth help is available:

    svk help environment    Environment variables that alter svk's behavior
    svk help commands       A list of all available commands
    svk help view           svk view support
    svk help <command-name> Help for a specific command

For commercial support, contact sales@bestpractical.com.  For up to date 
information about SVK, visit L<http://svk.bestpractical.com/>.

=cut
