#!/bin/sh

# Contribued by Jesse Vincent

# This helper script will call apple's "FileMerge" tool with the correct
# arguments for svk.

# $1  Working label   configure.ac (YOURS)
# $2  Working file    /tmp/svk-mergeP0xhK.tmp
# $3  Ancestor label  configure.ac (BASE)
# $4  Ancestor file   /tmp/svk-merge9adFA.tmp
# $5  Foreign label   configure.ac (THEIRS)
# $6  Foreign file    /tmp/svk-mergeUgPfz.tmp
# $7  Target file     svk-mergeFa4Rp

echo "Left: $1 Right: $3  Ancestor: $5  Target file: $7"

/Developer/Applications/Utilities/FileMerge.app/Contents/MacOS/FileMerge -left $2 -right $4 -ancestor $6 -merge $7
